[package]
name = "discord-prediction-market-bot"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.66"
chrono = "0.4.23"
chrono-english = "0.1.7"
chrono-tz = "0.8.1"
derive_more = "0.99.17"
fuzzy-matcher = "0.3.7"
im = { version = "15.1.0", features = ["serde"] }
poise = "0.5.0"
serde = "1.0.149"
serde_json = "1.0.89"
tokio = { version = "1.24.2", features = ["rt-multi-thread"] }
